# Generated by Django 5.2.8 on 2025-11-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Onay Bekliyor"),
                    ("APPROVED", "Onaylandı"),
                    ("REJECTED", "Reddedildi"),
                ],
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
