# Generated by Django 5.2.8 on 2025-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TASK_ASSIGNED", "Görev Atandı"),
                    ("TASK_COMPLETED", "Görev Tamamlandı"),
                    ("EVENT_REMINDER", "Etkinlik Hatırlatma"),
                    ("EVENT_CREATED", "Yeni Etkinlik"),
                    ("PROJECT_ASSIGNED", "Projeye Atandı"),
                    ("LEVEL_UP", "Seviye Atlama"),
                    ("ACHIEVEMENT", "Başarı Kazanıldı"),
                    ("REPORT_RESOLVED", "Rapor Çözüldü"),
                    ("REPORT_PENALTY", "Rapor Cezası"),
                    ("COMMENT", "Yorum Yapıldı"),
                    ("MENTION", "Bahsedildi"),
                    ("SYSTEM", "Sistem Bildirimi"),
                ],
                max_length=20,
            ),
        ),
    ]
