# Generated by Django 5.2.8 on 2025-11-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Proje Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANLAMA", "Planlama"),
                            ("AKTIF", "Aktif"),
                            ("BEKLEMEDE", "Beklemede"),
                            ("TAMAMLANDI", "Tamamlandı"),
                            ("IPTAL", "İptal"),
                        ],
                        default="PLANLAMA",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("DUSUK", "Düşük"),
                            ("ORTA", "Orta"),
                            ("YUKSEK", "Yüksek"),
                            ("KRITIK", "Kritik"),
                        ],
                        default="ORTA",
                        max_length=10,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarih"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, verbose_name="Toplam Puan"),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(default=0, verbose_name="Tamamlanma %"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Etiketler"
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(blank=True, verbose_name="Repository URL"),
                ),
                (
                    "documentation_url",
                    models.URLField(blank=True, verbose_name="Dokümantasyon URL"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proje Sahibi",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Takım Üyeleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje",
                "verbose_name_plural": "Projeler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Yorum")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje Yorumu",
                "verbose_name_plural": "Proje Yorumları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Görev")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("YAPILACAK", "Yapılacak"),
                            ("DEVAM_EDIYOR", "Devam Ediyor"),
                            ("TAMAMLANDI", "Tamamlandı"),
                        ],
                        default="YAPILACAK",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("DUSUK", "Düşük"),
                            ("ORTA", "Orta"),
                            ("YUKSEK", "Yüksek"),
                        ],
                        default="ORTA",
                        max_length=10,
                        verbose_name="Öncelik",
                    ),
                ),
                ("points", models.IntegerField(default=5, verbose_name="Puan")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarih"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan Kişi",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje Görevi",
                "verbose_name_plural": "Proje Görevleri",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "is_active"], name="projects_pr_status_163197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="projects_pr_owner_i_dea3a1_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="projects_pr_created_6b02e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["project", "status"], name="projects_pr_project_4795b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["assigned_to"], name="projects_pr_assigne_23e72d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(fields=["order"], name="projects_pr_order_6ea61e_idx"),
        ),
    ]
