# Generated by Django 5.2.8 on 2025-11-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_committee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Onay Bekliyor"),
                    ("APPROVED", "Onaylandı"),
                    ("REJECTED", "Reddedildi"),
                ],
                default="APPROVED",
                max_length=20,
                verbose_name="Onay Durumu",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Onaylanma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Onaylayan",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Red Sebebi"),
        ),
    ]
