# Generated by Django 5.2.8 on 2025-11-29 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0002_committeechatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Toplantı Türü"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "color",
                    models.CharField(
                        default="#dc2626", help_text="Hex renk kodu", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Toplantı Türü",
                "verbose_name_plural": "Toplantı Türleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Toplantı Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("date_time", models.DateTimeField(verbose_name="Tarih ve Saat")),
                ("location", models.CharField(max_length=200, verbose_name="Lokasyon")),
                (
                    "duration",
                    models.IntegerField(default=60, help_text="Süre (dakika)"),
                ),
                (
                    "is_general",
                    models.BooleanField(default=False, verbose_name="Genel Toplantı"),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="meeting_qr/"),
                ),
                (
                    "qr_data",
                    models.CharField(
                        blank=True, help_text="QR kod verisi", max_length=500
                    ),
                ),
                ("qr_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Toplantı Notları"),
                ),
                (
                    "decisions",
                    models.TextField(blank=True, verbose_name="Kararlar ve Aksiyonlar"),
                ),
                ("notes_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="committees.committee",
                        verbose_name="Komite",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "notes_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_meeting_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="meetings.meetingtype",
                        verbose_name="Toplantı Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toplantı",
                "verbose_name_plural": "Toplantılar",
                "ordering": ["-date_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="QR Taranma Tarihi"
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="Katıldı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                        verbose_name="Toplantı",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toplantı Katılımcısı",
                "verbose_name_plural": "Toplantı Katılımcıları",
                "ordering": ["-scanned_at"],
                "unique_together": {("meeting", "user")},
            },
        ),
    ]
