# Generated by Django 5.2.8 on 2025-11-29 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("KOMITE", "Komite Toplantısı"),
                    ("GENEL_KURUL", "Genel Kurul"),
                    ("EGITIM", "Eğitim"),
                    ("KOORDINASYON", "Koordinasyon"),
                    ("DIGER", "Diğer"),
                ],
                default="standart",
                max_length=20,
                verbose_name="Toplantı Türü",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="notes_updated_at",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="notes_updated_by",
        ),
        migrations.AddField(
            model_name="meeting",
            name="actions",
            field=models.TextField(
                blank=True,
                help_text="Aksiyonlar ve sorumluları",
                verbose_name="Aksiyonlar",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="agenda_items",
            field=models.TextField(
                blank=True,
                help_text="Gündem maddeleri (her satır bir madde)",
                verbose_name="Gündem Maddeleri",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, verbose_name="Hatırlatma Gönderildi"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="decisions",
            field=models.TextField(
                blank=True, help_text="Alınan kararlar", verbose_name="Kararlar"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="duration",
            field=models.IntegerField(
                default=60, help_text="Süre (dakika)", verbose_name="Süre"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="is_general",
            field=models.BooleanField(
                default=False,
                help_text="Genel toplantı mı? (Komite dışı)",
                verbose_name="Genel Toplantı",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="meeting_qr/", verbose_name="QR Kod"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="qr_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="QR Kod Son Geçerlilik"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.CreateModel(
            name="MeetingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Taranma Tarihi"
                    ),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Kazanılan Puan"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="İptal Edildi"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İptal Tarihi"
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="İptal Sebebi"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_meeting_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İptal Eden",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="meetings.meeting",
                        verbose_name="Toplantı",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toplantı Katılımı",
                "verbose_name_plural": "Toplantı Katılımları",
                "ordering": ["-scanned_at"],
                "unique_together": {("meeting", "user")},
            },
        ),
        migrations.DeleteModel(
            name="MeetingParticipant",
        ),
        migrations.DeleteModel(
            name="MeetingType",
        ),
    ]
