# Generated by Django 5.2.8 on 2025-11-15 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(help_text="Kazanılan veya kaybedilen puan"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("EVENT", "Etkinlik"),
                            ("TASK", "Görev"),
                            ("PROJECT", "Proje"),
                            ("MANUAL", "Manuel (Admin)"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True,
                        help_text="İlgili kaynak ID (event, task, project)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Puan açıklaması"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aktivite Logu",
                "verbose_name_plural": "Aktivite Logları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LevelThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_points",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "verbose_name": "Seviye Eşiği",
                "verbose_name_plural": "Seviye Eşikleri",
                "ordering": ["level"],
            },
        ),
    ]
