# Generated by Django 5.2.8 on 2025-11-15 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin tarafından eklendiyse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["-created_at"], name="activity_ac_created_d34040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="activity_ac_user_id_9aae35_idx"
            ),
        ),
    ]
