# Generated by Django 5.2.8 on 2025-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_alter_activitylog_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="source",
            field=models.CharField(
                choices=[
                    ("EVENT", "Etkinlik"),
                    ("TASK", "Görev"),
                    ("PROJECT", "Proje"),
                    ("EFFORT", "Efor"),
                    ("EFFORT_UPDATE", "Efor Güncelleme"),
                    ("MEETING", "Toplantı"),
                    ("MANUAL", "Manuel (Admin)"),
                    ("REPORT", "Rapor Cezası"),
                    ("OTHER", "Diğer"),
                ],
                max_length=20,
            ),
        ),
    ]
