# Generated by Django 5.2.8 on 2025-12-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activitylog_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Yıl (2025, 2026...)')),
                ('month', models.IntegerField(help_text='Ay (1-12)')),
                ('winning_points', models.IntegerField(default=0, help_text='Kazanan puan')),
                ('leaderboard_snapshot', models.JSONField(default=list, help_text='O ayın top 10 kullanıcısı [{user_id, username, points, rank}, ...]')),
                ('is_finalized', models.BooleanField(default=False, help_text='Ay sonunda finalize edildi mi?')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winners', models.ManyToManyField(help_text='Ayın parlayan yıldızları', related_name='monthly_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aylık Lider Tablosu',
                'verbose_name_plural': 'Aylık Lider Tabloları',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['-year', '-month'], name='activity_mo_year_2deca5_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UserMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0, help_text='O ay toplanan puan')),
                ('rank', models.IntegerField(blank=True, help_text='O ayki sıralama', null=True)),
                ('is_winner', models.BooleanField(default=False, help_text='Ayın yıldızı mı?')),
                ('events_attended', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('projects_contributed', models.IntegerField(default=0)),
                ('meetings_attended', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aylık İstatistik',
                'verbose_name_plural': 'Kullanıcı Aylık İstatistikleri',
                'ordering': ['-year', '-month', '-points_earned'],
                'indexes': [models.Index(fields=['user', '-year', '-month'], name='activity_us_user_id_e1e226_idx'), models.Index(fields=['-year', '-month', '-points_earned'], name='activity_us_year_6e72ed_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
