# Generated by Django 5.2.8 on 2025-11-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "__first__"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu görevi sadece seçilen komite üyeleri görebilir ve alabilir",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="committees.committee",
                verbose_name="Komite",
            ),
        ),
    ]
