# Generated by Django 5.2.8 on 2025-11-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_approval_status_task_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Göreve atanan birden fazla kişi",
                related_name="assigned_tasks_multi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atanan Kişiler",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: assigned_users kullanın",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atanan Kişi",
            ),
        ),
    ]
