# Generated by Django 5.2.8 on 2025-11-29 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_assigned_users_alter_task_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                help_text="Görev iptal edildiğinde sebep",
                verbose_name="İptal Sebebi",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="İptal Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="İptal Eden",
            ),
        ),
    ]
