# Generated by Django 5.2.8 on 2025-11-30 10:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0002_committeechatmessage"),
        ("projects", "0003_project_approval_status_project_approved_at_and_more"),
        ("tasks", "0005_task_cancellation_reason_task_cancelled_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Effort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("PROJE", "Proje"),
                            ("GOREV", "Görev"),
                            ("GENEL", "Genel Çalışma"),
                            ("EGITIM", "Eğitim"),
                            ("ARASTIRMA", "Araştırma"),
                            ("TOPLANTI", "Toplantı"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Çalışma Türü",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Çalışma süresi dakika cinsinden",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Süre (Dakika)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Ne çalışıldı? Kısa açıklama",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Tarih",
                    ),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Kazanılan Puan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="efforts",
                        to="committees.committee",
                        verbose_name="Komite",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hangi proje için çalışıldı?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="efforts",
                        to="projects.project",
                        verbose_name="Proje",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hangi görev için çalışıldı?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="efforts",
                        to="tasks.task",
                        verbose_name="Görev",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efforts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Efor",
                "verbose_name_plural": "Eforlar",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EffortComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Yorum")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yorum Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "effort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="efforts.effort",
                        verbose_name="Efor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effort_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Efor Yorumu",
                "verbose_name_plural": "Efor Yorumları",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EffortLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Beğenilme Tarihi"
                    ),
                ),
                (
                    "effort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="efforts.effort",
                        verbose_name="Efor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effort_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Efor Beğenisi",
                "verbose_name_plural": "Efor Beğenileri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="effort",
            index=models.Index(
                fields=["-date", "-created_at"], name="efforts_eff_date_79e2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="effort",
            index=models.Index(
                fields=["user", "-date"], name="efforts_eff_user_id_6b00bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="effort",
            index=models.Index(
                fields=["committee", "-date"], name="efforts_eff_committ_4859b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="effort",
            index=models.Index(
                fields=["work_type", "-date"], name="efforts_eff_work_ty_83f68f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="effort",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gte", 1)),
                name="duration_minutes_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="effortcomment",
            index=models.Index(
                fields=["effort", "created_at"], name="efforts_eff_effort__25d0d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="effortlike",
            index=models.Index(
                fields=["effort", "-created_at"], name="efforts_eff_effort__412cd1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="effortlike",
            unique_together={("effort", "user")},
        ),
    ]
