# Generated by Django 5.2.8 on 2025-11-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("committees", "0002_committeechatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Oda Adı")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Genel Chat"),
                            ("COMMITTEE", "Komite Chat"),
                            ("PRIVATE", "Özel Mesaj"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "committee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_room",
                        to="committees.committee",
                        verbose_name="Komite",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Katılımcılar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Odası",
                "verbose_name_plural": "Chat Odaları",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Metin"),
                            ("image", "Resim"),
                            ("file", "Dosya"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Okuyanlar",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderen",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chatroom",
                        verbose_name="Oda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Mesajı",
                "verbose_name_plural": "Chat Mesajları",
                "ordering": ["created_at"],
            },
        ),
    ]
