# Generated by Django 5.2.8 on 2025-11-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
        ("projects", "0003_project_approval_status_project_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="projects.project",
                verbose_name="Proje",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Genel Chat"),
                    ("COMMITTEE", "Komite Chat"),
                    ("PRIVATE", "Özel Mesaj"),
                    ("PROJECT", "Proje Chat"),
                ],
                default="PRIVATE",
                max_length=20,
            ),
        ),
    ]
