# Generated by Django 5.2.8 on 2025-11-15 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Komite Adı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Komite Lideri",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Üyeler",
                    ),
                ),
                (
                    "vice_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vice_led_committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Komite Başkan Yardımcısı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komite",
                "verbose_name_plural": "Komiteler",
                "ordering": ["name"],
            },
        ),
    ]
