# Generated by Django 5.2.8 on 2025-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("BASKAN", "Başkan"),
                    ("BASKAN_YARDIMCISI", "Başkan Yardımcısı"),
                    ("BIRIM_BASKANI", "Birim Başkanı"),
                    ("KOMITE_LIDERI", "Komite Lideri"),
                    ("KOMITE_YARDIMCISI", "Komite Başkan Yardımcısı"),
                    ("UYE", "Üye"),
                ],
                default="UYE",
                max_length=20,
            ),
        ),
    ]
