# Generated by Django 5.2.8 on 2025-11-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                choices=[
                    (1, "Başlangıç"),
                    (2, "Temel"),
                    (3, "Orta"),
                    (4, "İyi"),
                    (5, "Uzman"),
                ],
                default=1,
                help_text="Yetenek seviyesi (1-5)",
            ),
        ),
    ]
