# Generated by Django 5.2.8 on 2025-11-26 13:46

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_online_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profil resmi (Max 5MB, jpg/png/gif/webp)",
                null=True,
                upload_to="profiles/",
                validators=[
                    users.validators.validate_image_size,
                    users.validators.validate_image_extension,
                ],
            ),
        ),
    ]
