# Generated by Django 5.2.8 on 2025-11-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_points__gte", 0)),
                name="total_points_non_negative",
            ),
        ),
    ]
