# Generated by Django 5.2.8 on 2025-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_total_points_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='total_points_non_negative',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
