# Generated by Django 5.2.8 on 2025-12-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_total_points_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('website', 'Kişisel Website'), ('medium', 'Medium'), ('youtube', 'YouTube'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('other', 'Diğer')], help_text='Platform türü', max_length=20)),
                ('title', models.CharField(help_text="Başlık (ör: 'LinkedIn Profilim', 'Portfolio')", max_length=50)),
                ('url', models.URLField(help_text="Link URL'i", max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Gösterim sırası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sosyal Link',
                'verbose_name_plural': 'Sosyal Linkler',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
