# Generated by Django 5.2.8 on 2025-12-22 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star_count',
            field=models.IntegerField(default=0, help_text="Kaç kez 'Ayın Parlayan Yıldızı' oldu", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
