# Generated by Django 5.2.8 on 2025-12-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_star_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
    ]
